from ast import parse
import textract
from stop_words import get_stop_words
from nltk.corpus import stopwords
import PyPDF2

def parse_cv(file):
  pdf = file.name.split('.')[-1] == 'pdf'

  if not pdf:
    return 15, 7, 0, 'filippovarini'

  company_score = 0
  language_score = 0
  buzzword_score = 0
  github_link = ""
  strings_to_remove = ["&","-"]

  text = PyPDF2.PdfFileReader(file)

  companies = ["Expensify", "Motional", "Gusto", "Hudson River Trading", "Bridgewater Associates", "Credit Suisse", "BlackStone", "PWC", "AQR", "Optiver", "Caterpillar","Schneider Downs","GE","Second Order Effects", "Morgan Stanley", "Bessemer Ventures Fellowship", "Audible", "KeyBank", "General Motors", "Susquehanna", "Five Rings", "Akuna Capital", "D. E. Shaw", "Toyota","Vanguard", "Salesforce", "RBC Capital Markets", "Asana", "Target", "BNP Paribas", "MealMe", "Apple", "Meta", "Goldman Sachs", "BlackRock", "Bank of America", "Two Sigma", "Cigna", "Bracebridge Capital", "Federated Insurance", "US Ventures", "Amazon", "AWS", "Palantir", "Tableau", "McKinsey", "Nvidia", "Cisco", "Tower Research Capital", "Jane Street", "PayPal", "Barclays", "Lenovo", "Belvedere Trading", "C.H. Robinson", "Benchling", "Raymond Corporation", "DRW", "Oracle", "Citadel Securities", 	"Microsoft", "Aldridge Electric", "VMware", "Fifth Third Bank", "Red Venture", "Prudential Financial", "Pimco", "Collins Aerospace", "IMC", "Dick's Sporting Goods", "Citi Bank", "Conagra Brands", "P&G", "Raytheon Technologies", "RSM", "Freddie Mac", "Nestle", "L3Harris Technologies", "PEAK6", "Citrix", "Qualtrics", "Virtu Financial","MathWorks", "Redfi", "Quantco","Virgin Orbit","Crestron","JP Morgan","Dropbox","Cargill","Johnson Controls","HubSpot","Clever","Robinhood","Jina AI","TomTom","Walmart","Duolingo","Nuro.ai","Capital One","Hyperscience","Jump Trading","Cox Automotive","IBM","Affirm","Chapter","Okta","Pearson","Commerce Bank","Garmin","Medtronic","Aechelon Technology","Stripe","UnitedHealth","SAP","Samsara","Datadog","Quora","Air Products","TD Banks","Neocis","Convoy","Visa","Anduril","Verkada","Steelcase","Kapwing","F5 Network","Wabtec","Crown Equipment Corporation","Lyft","Johnson & Johnson","3M","Twitch","Verisk","Snackpass","Roblox","Peraton","Noblis","Appian Corp","Figma","Rippling","Principal Financial Group","Gem","Veeva","Persona","Guardian Life","Honda","Daktronics","AArete","Snap","Quip","Chime","Urban Outfitters","Innovative Systems","OnPrem Solution Partners","Belcan","Unilever","Silicon Labs","Zoom","Zebra Technologies","TuSimple","Ocient","Texas Instruments","Amazon Robotics","Wells Fargo","DataBricks","Pinterest","Plaid","Mastercard","Bloomberg","Twilio","Factset","Leidos","Broadway Technology","Asurion","Yext","PatientCo","24G","ServiceNow","Quantcast","U.S Bank","NetApp","FireEye","Uline","Blend","Motional","Hudl","Paylocity","OSISoft","Valkyrie Trading","Revantage","Chick-fil-a","AvidXchange","ZS Associates","Deutsche Bank","General Dynamics Mission Systems","Rivian","DoorDash","Mr. Cooper Group","UIPath","Uber","Workiva","SingleStore","Vail Systems","Domeyard","Vermeer","Federal Reserve System","WeRide.ai","Mutual of Omaha","TikTok","Microfocus","Linkedin","Wipfli","Ford Motor Company","DraftKings","CrowdStrike","Riot Games","John Hopkins APL","Sealed Air Corporation","Ampere","Schonfeld","Vise","Thomson Reuters","Viasat","TJX","Textron","Discovery Inc","NASA Jet Propulsion Laboratory","McDonald's","MongoDB","QVC","DriveTime","Plexus","Slack","Waymo","Geico","Indeed","LightBox","MarketAxess Corporation","HP","Xylem","Chicago Trading Company","American Express","Dimensional Fund","Anyscale","Snorkel AI","Netflix","Slalom","Charles Schwab","Pella","Ultimate Kronos Group","Dell","Squarespace","Publicis Sapient","Nike","ASML","Aloft","Relativity","Honeywell","CACI","Hilti","Battelle","C3.AI","Duke Energy Corporation","ByteDance","Nutrien","Expedia","Intel","Pocket Gems","Neeva","SpaceX","New Relic","Abrigo","Allegion","Chan Zuckerberg Initiative","Kiva","OppFi","KnowBe4","Nutanix","Blue Cross Blue Shield of Michigan","Bentley","Google","Shure Inc","X By 2","Trimble","Victoria's Secret","Gordian","Ginkgo Bioworks","Cloudera","Aegon","TransAmerica","Baxter International","iRobot","Northwestern Mutual","Flatiron","Equipment Share","Vectorworks","Aegon","TransAmerica","Samsung","Playstation","Genesys","McKesson","Toast","Avanade","Intuit","Optum","Splunk","Gap","Checkr","Intuitive","Twitter","Workday","Epic Games","Pacific Northwest National Laboratory","Instabase","Red Hat","DataChat","HashiCorp","Brex","Atlassian","Square","T-Mobile","American Airlines","Second Spectrum","Bankers Healthcare Group","FanDuel","Voleon","Alteryx","Aurora","Analog Devices","Addepar","Cloudflare","Cambly","Qumulo","Pendo","PathAI","Reddit","Bodo.ai","GitLab","Lumen Technologies","Yahoo","Unisys","MailChimp","Adobe","Flexport","Airbnb","Ping Identity","Certik","Roku","Rokt","Olive","Duquesne Light","Vistaprint","Snowflake","Regeneron Pharmaceuticals","Tesla","Replicon","Circle","Spotify","Justworks","Braze","Cohesity","Autodesk","Equifax","Copart","Home Depot","Mark43","Lucid"]
  languages = ["Python","Java","JavaScript","C#","C","C++","PHP","R","Swift","Objective-C","Matlab","TypeScript","Go","Kotlin","VBA","Rust","Ruby","Ada","Scala","Dart","Abap","Groovy","Lua","Julia","Perl","Haskell","Cobol"]
  buzzwords = [
    '4g',
    '5g',
    'accountable',
    'talk',
    'agile',
    'ajax',
    'algorithm',
    'alignment',
    'ambiguity',
    'amplify',
    'analytics',
    'andon',
    'api',
    'artisan',
    'back-end',
    'ballpark',
    'bandwidth',
    'benchmarking',
    'best',
    'practices',
    'beta',
    'data',
    'society',
    'bio',
    'bizmeth',
    'bleeding',
    'blockchain',
    "taxonomy",
    'capabilities',
    'outsourcing',
    'business-to-business',
    'business-to-consumer',
    'buzzword',
    'compliant',
    'cadence',
    'catchphrase',
    'clear goal',
    'clickthrough',
    'client-centric',
    'close the loop',
    'cloud-computing',
    'co-opetition',
    'collaboration',
    'come-to-jesus',
    'common',
    'core',
    'content',
    'management',
    'system',
    'marketing',
    'convergence',
    'competency',
    'corporate',
    'coward',
    'creative',
    'cross-platform',
    'css3',
    'customer-centric',
    'cyber-physical',
    'mining',
    'science',
    'datafication',
    'deep',
    'dive',
    'learning',
    'web',
    'design',
    'devops',
    'differentiated',
    'instruction',
    'digital',
    'divide',
    'digital',
    'literacy',
    'digital',
    'remastering',
    'digital rights management',
    'digital signage',
    'disruptive innovation',
    'disruptive technologies',
    'diversity',
    'document management',
    'dot-bomb',
    'downsizing',
    'drill down',
    'drinking the kool-aid',
    'e-learning',
    'early-stage',
    'eating your own dogfood',
    'eco-',
    'emotional intelligence',
    'employer branding',
    'empowerment',
    'enable',
    'end-to-end',
    'engine',
    'enterprise content management',
    'enterprise service bus',
    'entitlement',
    'ephemeral rogue entity',
    'establishment',
    'evangelist',
    'event horizon',
    'exit strategy',
    'eyeballs',
    'face time',
    'fit for purpose',
    'fleet dynamism',
    'flipped classroom',
    'folksonomy',
    'framework',
    'free value',
    'frictionless',
    'front-end',
    'fulfilment issues',
    'fuzzy logic',
    'generation x',
    'generation y',
    'globalization',
    'going forward',
    'grow',
    'growth hacking',
    'guided reading',
    'headlights',
    'heavy lifting',
    'herding cats',
    'higher-order thinking',
    'holistic',
    'holistic approach',
    'home',
    'html5',
    'hype cycle',
    'hyperlocal',
    'iaas',
    'ideation management',
    'immersion',
    'impact',
    'information society',
    'information superhighway',
    'innovation',
    'innovative',
    'instructional scaffolding',
    'internet of things',
    'invested in',
    'javascript',
    'knowledge process outsourcing',
    'lambda',
    'lateral violence',
    'law of the instrument',
    'leverage',
    'list of buzzwords',
    'logistics',
    'long tail',
    'low hanging fruit',
    'machine learning',
    'make it pop',
    'management visibility',
    'marketing buzz',
    'mashup',
    'memetics',
    'microservices',
    'millennial',
    'mind share',
    'mindshare',
    'mission critical',
    'mobile',
    'modularity',
    'mouthfeel',
    'moving forward',
    'multiple intelligences',
    'nanotechnology',
    'national security',
    'netiquette',
    'new economy',
    'new normal',
    'next generation',
    'offshoring',
    'on the runway',
    'one team',
    'open source',
    'opportunities',
    'optics',
    'organic growth',
    'paas',
    'pain point',
    'paradigm',
    'shift',
    'analysis',
    'passionate',
    'pleonasm',
    'podcasting',
    'political',
    'capital',
    'power',
    'word',
    'privacy',
    'proactive',
    'productivity',
    'profit',
    'center',
    'project-based',
    'learning',
    'psychobabble',
    'quantum',
    'supremacy',
    'real-time',
    'reimagine',
    'resonate',
    'web',
    'design',
    'investment',
    'fulfilment',
    'rightshoring',
    'roadmap',
    'robust',
    'business',
    'rustic',
    'saas',
    'scalability',
    'sea change',
    'seamless',
    'sensorization',
    'serum',
    'share',
    'options',
    'sisterhood',
    'skeuomorphic',
    'social bookmarking',
    'social software',
    'software defined networking',
    'solidarity',
    'solution',
    'sox',
    'spa',
    'spam',
    'spin-up',
    'stack',
    'stakeholder',
    'startup',
    'storytelling',
    'strategic communication',
    'strategic ineptness',
    'streamline',
    'student engagement',
    'survival strategy',
    'sustainability',
    'sync-up',
    'synergy',
    'systems',
    'development',
    'life-cycle',
    'tagging',
    'take offline',
    'talent',
    'relationship',
    'management',
    'think outside the box',
    'tiger team',
    'time-blindness',
    'toolchain',
    'touchpoint',
    'transmedia',
    'unpack',
    'value',
    'add',
    'value-added',
    'viral',
    'virtualization',
    'virtue',
    'word',
    'visibility',
    'vortal',
    'warfighter',
    'web 2.0',
    'web services',
    'webinar',
    'wellness',
    'wheelhouse',
    'wikiality',
    'win-win',
    'work smarter',
    'workflow'
  ]

  company_key_words = []
  for company in companies:
      for keyword in company.split():
          company_key_words.append(keyword)
  company_key_words = list(dict.fromkeys(company_key_words))
  filtered_words = [word for word in text if word not in stopwords.words('english')]
  filtered_words = list(set(filtered_words) - set(strings_to_remove))

  tech_stack = []

  for word in filtered_words:
      if (("github.com" in word) or ("github/" in word)):
          github_link = word

      #Company score
      for key_word in company_key_words:
          if key_word.upper() == word.upper():
              company_score += 1

      #Language score
      for prog_lang in languages:
          if prog_lang.upper() == word.upper():
              language_score += 1
              tech_stack.append(prog_lang)  

      #Buzzword score
      for phrase in buzzwords:
          if phrase.upper == word.upper():
              buzzword_score += 1

  #github = scan_github(github_link)
  return (company_score, language_score, buzzword_score, github_link)